version: '3'

services:
  php:
    container_name: php-dev
    restart: always
    build:
      context: ./php
    volumes:
      - ../html:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 9000:9000

  nginx:
    container_name: webserver
    restart: always
    build:
      context: ./nginx
    volumes:
      - ../html:/var/www/html/
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80

  database:
    container_name: database
    build:
      context: ./database
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=priisoft_hcuconf
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=pwdsecret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOSTS: database
